### ISSUE TITLE
Can't set item prices for +$999

### ISSUE THREAD

**Issue by OctavioFariasDamian** [brcdev-minecraft/shopgui-api#39]
For any reason, the plugin don't let load items with more than $999 price of buy or sell, and it is setted to the first digit:

```YAML
16:
      type: item
      item:
        material: ENCHANTED_GOLDEN_APPLE
        quantity: 1
      buyPrice: 9000
      sellPrice: -1
      slot: 29
```
![image](https://github.com/user-attachments/assets/af995550-e5fc-4708-ab19-64a28b5cc65e)
